name: Java CI/CD Pipeline

on:
  push:
    branches: [main, develop]

jobs:
  compileAndTest:
    runs-on: self-hosted

    steps:
    - name: code checkout
      uses: actions/checkout@v4.2.2
    - name: set up Java JDK
      uses:  actions/setup-java@v4.7.1
      with: 
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
    - name: Compile build
      run: mvn clean compile
    - name: Run unit tests
      run: mvn clean test

  securityCheck:
    runs-on: self-hosted
    needs: compileAndTest

    steps: 
    - name: Install trivy
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
        
    - name: Run trivy
      run: trivy fs . --format json --output trivy-report.json

    - name: Install Gitleaks
      run: |
         curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_x64.tar.gz | tar -xz
         sudo mv gitleaks /usr/local/bin

    - name: Run Gitleaks
      run: |
        gitleaks detect --source . --report-format json --report-path gitleaks-report.json --exit-code 1

  
      
